### ISSUE TITLE
Vault plugin assume aws stemcell

### ISSUE THREAD

**Issue by dwallraff** [enaml-ops/omg-product-bundle#1]
The vault plugin seems to assume you're deploying to AWS.
If you ignore the `os:` tag and use the URL as is rather than piecing together the url from the flags, it should work.

```
--stemcell-url https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.2-google-kvm-ubuntu-trusty-go_agent.tgz \
--stemcell-ver 3262.2 \
--stemcell-sha f46d82a6ae6e89a5635cb3122389f0c8459a82e0 \
--stemcell-name ubuntu-trusty
```

leads to:

```
stemcells:
- alias: ubuntu-trusty
  os: bosh-aws-xen-ubuntu-trusty-go_agent
  version: "3262.2"
  url: https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.2-google-kvm-ubuntu-trusty-go_agent.tgz?v=3262.2
  sha1: f46d82a6ae6e89a5635cb3122389f0c8459a82e0
```

should be:

```
stemcells:
- alias: ubuntu-trusty
  os: ubuntu-trusty
  version: "3262.2"
  url: https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.2-google-kvm-ubuntu-trusty-go_agent.tgz
  sha1: f46d82a6ae6e89a5635cb3122389f0c8459a82e0
```
