### ISSUE TITLE
stemcell alias not replaced in cloudfoundry plugin

### ISSUE THREAD

**Issue by warroyo** [enaml-ops/omg-product-bundle#17]
when running the omg-cli with the `cloudfoundry-plugin-linux` all instances of of "stemcell" in the instance_groups are replaces with the value from  `--stemcell-name` however the initial "stemcells" yml entry does not replace the "alias" field. see below

````
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3263.7"
instance_groups:
- name: consul-partition
  instances: 1
  vm_type: nano
  stemcell: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  azs: [AZ1]
````

notice the "alias" is "trusty" this causes the deployment to fail due to missing stemcell.
