### ISSUE TITLE
ert-plugin v0.0.6-2c316c generates invalid fingerprints

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/omg-product-bundle#22]
ert-plugin v0.0.6-2c316c generates invalid fingerprints.

It produces something like this:

```
instance_groups:
- name: cloud_controller-partition
  jobs:
  - name: cloud_controller_ng
    properties:
      app_ssh:
        host_key_fingerprint: "hyqgbedosdn7886qvxs90"
```

But should instead product the fingerprint of the host key, like:

```
instance_groups:
- name: cloud_controller-partition
  jobs:
  - name: cloud_controller_ng
    properties:
      app_ssh:
        host_key_fingerprint: "ad:6a:47:ca:8b:ee:ef:25:2a:78:04:f2:12:35:04:a2"
```
