### ISSUE TITLE
redis product plugin generates a manifest for old version of BOSH.

### ISSUE THREAD

**Issue by allomov** [enaml-ops/omg-product-bundle#27]
It is imposible to use BOSH manifest generated by redis product plugin with BOSH with cloudconfig.

**Comment by zmb3** [comment]
All omg manifests support (and require) BOSH with cloud config.
Are you sure your issue isn't somewhere else?

**Comment by allomov** [comment]
I had a number of issues with redis manifest created through omg. I need to add that I use golang bosh-cli to deploy.

**Comment by zmb3** [comment]
This issue is not actionable as written, so I'm going to close it.  Please feel free to reopen it or open a new issue if you identify a specific problem.

**Comment by allomov** [comment]
First error is `Property 'persistent_disk' value ("4096") did not match the required type 'Integer'`. When I replace `"4096"` with `4096` in the manifest, I get the following error 
```
Error: Instance group 'redis_leader_z1' references an unknown resource pool 'medium'
```
I definitely have `'medium'` in `vm_types` section in cloud config. But yes, the main reason is that I am using golang bosh-cli.

**Comment by allomov** [comment]
Tried with `bosh_cli` gem and got the same error. 

```
Director task 486
  Started preparing deployment > Preparing deployment. Failed: Instance group 'redis_leader_z1' references an unknown resource pool 'medium' (00:00:00)

Error 140003: Instance group 'redis_leader_z1' references an unknown resource pool 'medium'

Task 486 error

For a more detailed error report, run: bosh task 486 --debug
```
and there is `medium` `vm_type` in my cloud config:
```
# bosh cloud-config | grep -C 4 medium
Acting as client 'director' on 'wdc1'
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
compilation:
  az: az1
  network: pcf-management
  reuse_compilation_vms: true
  vm_type: medium
  workers: 8
disk_types:
- cloud_properties:
    disk_flavor: core-200
--
  name: small
- cloud_properties:
    disk_flavor: core-200
  disk_size: 30000
  name: medium
- cloud_properties:
    disk_flavor: core-200
  disk_size: 50000
  name: large
--
    vm_flavor: core-200
  env:
    bosh:
      password: ""
  name: medium
- cloud_properties:
    disk_flavor: core-200
    vm_attached_disk_size_gb: 50
    vm_flavor: core-240
```
