### ISSUE TITLE
[Concourse] Expose Proxy Settings and Additional Resources

### ISSUE THREAD

**Issue by RRRII** [enaml-ops/omg-product-bundle#28]
Can the following flags from the Concourse Groundcrew job be exposed in the Concourse plugin?

```
  http_proxy_url:
    description: |
      Proxy to use for outgoing http requests from containers.

  https_proxy_url:
    description: |
      Proxy to use for outgoing https requests from containers.

  no_proxy:
    description: |
      A list domains and IPs with optional port for which the proxy should be bypassed, e.g. [localhost, 127.0.0.1, example.com, domain.com:8080]
    default: []

  additional_resource_types:
    description: |
      Additional resource types supported by the workers in `[{type: string, image: string}]` format.
    default: []
```
